var data = [
		{
			"name":"海阔天空",
			"singer":"黄家驹",
			"album":"海阔天空",
			"price":"25",
			"delete":"删除"
		},
		{
			"name":"半壶沙",
			"singer":"刘珂矣",
			"album":"半壶沙",
			"price":"28",
			"delete":"删除"
		},
		{
			"name":"Are Not Alone",
			"singer":"Michael",
			"album":"Are Not Alone",
			"price":"26",
			"delete":"删除"
		},
		{
			"name":"光辉岁月",
			"singer":"beyond",
			"album":"黄家驹原创精选",
			"price":"51",
			"delete":"删除"
		},
		{
			"name":"最初的梦想",
			"singer":"范玮琪",
			"album":"2013跨年演唱会",
			"price":"23",
			"delete":"删除"
		},
		{
			"name":"我懂了",
			"singer":"金莎",
			"album":"我懂了",
			"price":"9",
			"delete":"删除"
		},
		{
			"name":"我最闪亮",
			"singer":"快乐男生",
			"album":"2007快乐男生主题曲",
			"price":"15",
			"delete":"删除"
		},
		{
			"name":"壮志在我胸",
			"singer":"群星",
			"album":"励歌曲",
			"price":"21",
			"delete":"删除"
		},
		{
			"name":"从头再来",
			"singer":"刘欢",
			"album":"经典20年",
			"price":"22",
			"delete":"删除"
		},
		{
			"name":"怒放的生命",
			"singer":"汪峰",
			"album":"怒放的生命",
			"price":"5",
			"delete":"删除"
		}
		
			]
